<?xml version="1.0" encoding="utf-8"?><Database Name="eczane" Class="DataClasses2DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-EQDG4D1;Initial Catalog=eczane;Integrated Security=True" SettingsObjectName="VTYS_Proje_App.Properties.Settings" SettingsPropertyName="eczaneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Kullanicilar1" Member="Kullanicilar1">
    <Type Name="Kullanicilar1">
      <Column Name="KullaniciID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="KullaniciAd" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Sifre" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="Ad" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SoyAd" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Yetki" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>